package com.example.demo.model;

public enum Department {

    GENERAL_MEDICINE("GENERAL MEDICINE"),
    GENERAL_SURGERY("GENERAL SURGERY"),
    PEDIATRICS("PEDIATRICS"),
    GYNECOLOGY_OBSTETRICS("GYNECOLOGY & OBSTETRICS"),
    ORTHOPEDICS("ORTHOPEDICS"),
    ENT("ENT"),
    OPHTHALMOLOGY("OPHTHALMOLOGY"),
    DERMATOLOGY("DERMATOLOGY"),
    PSYCHIATRY("PSYCHIATRY"),
    PULMONOLOGY("PULMONOLOGY"),

    CARDIOLOGY("CARDIOLOGY"),
    NEUROLOGY("NEUROLOGY"),
    NEUROSURGERY("NEUROSURGERY"),
    GASTROENTEROLOGY("GASTROENTEROLOGY"),
    NEPHROLOGY("NEPHROLOGY"),
    UROLOGY("UROLOGY"),
    ENDOCRINOLOGY("ENDOCRINOLOGY"),
    RHEUMATOLOGY("RHEUMATOLOGY"),
    HEMATOLOGY("HEMATOLOGY"),
    ONCOLOGY("ONCOLOGY"),

    RADIOLOGY("RADIOLOGY"),
    PATHOLOGY("PATHOLOGY"),
    ANESTHESIOLOGY("ANESTHESIOLOGY"),
    EMERGENCY_TRAUMA("EMERGENCY & TRAUMA"),
    CRITICAL_CARE_ICU("CRITICAL CARE (ICU)"),

    DENTISTRY("DENTISTRY"),
    PHYSIOTHERAPY("PHYSIOTHERAPY"),
    AYUSH("AYUSH");

    private final String displayName;

    Department(String displayName) {
        this.displayName = displayName;
    }

    public String getDisplayName() {
        return displayName;
    }
}
