spring.application.name=hospital_Project2025

# ================================
# SERVER CONFIGURATION
# ================================
server.port=8080

# ================================
# DATABASE CONFIGURATION (MySQL 8)
# ================================
# Replace 'hospital_db' with your actual database name
spring.datasource.url=jdbc:mysql://localhost:3306/hospital_2025?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=tisha141223

# ================================
# JPA / HIBERNATE CONFIGURATION 
# ================================
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# Isse tables automatic ban jayengi

# ================================
# JWT & BUSINESS LOGIC
# ================================
jwt.secret=H3LLoW0rLD!Th!sIs@My256BitJWTKey12345
jwt.expiration=3600000
hospital.email.domain=@wellspring.com

# ================================
# MAIL SERVICE (Gmail SMTP)
# ================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hospitalspringwell@gmail.com
spring.mail.password=bwbu rxsx scfn zesk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true